name: Myapp CI-CD

env:
    AZURE_WEBAPP_NAME: mysimplewebapp
    AZURE_WEBAPP_PACKAGE_PATH: '.' # default to repository root
    DOTNET_VERSION: '9.0.x'

defaults:
    run:
        shell: bash
        working-directory: ./mywebapp

on:
    push:
        branches: ['main']

    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest  ## this is a runner.
        steps:
            - uses: actions/checkout@v5 ## checkout the repository.

            - name: Set up .net Core
              uses: actions/setup-dotnet@v4   ## setting up the .net environment and it uses dotnet 9 version  
              with: 
                dotnet-version: ${{env.DOTNET_VERSION}}

            - name: Install dependencies
              run: dotnet restore

            - name: build with dotnet
              run: dotnet build --configuration Release

            - name: dotnet publish
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/testapp

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                name: dotnet-app
                path: ${{env.DOTNET_ROOT}}/testapp
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: 'Development'
            url: ${{steps.deploy-to-azure-web-app.outputs.webapp-url}}

        steps:
            - name: download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: dotnet-app

            - name: Azure Login
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to Azure Web App
              id: deploy-to-azure
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                package: dotnet-app
